# Shaarli - Docker Compose example configuration
#
# See:
# - https://shaarli.readthedocs.io/en/master/Docker/#docker-compose
#
# Environment variables:
# - SHAARLI_VIRTUAL_HOST      Fully Qualified Domain Name for the Shaarli instance
# - SHAARLI_LETSENCRYPT_EMAIL Contact email for certificate renewal
# - SHAARLI_DOCKER_TAG        Shaarli docker tag to use
#                             See: https://hub.docker.com/r/shaarli/shaarli/tags
version: '3'

services:
  shaarli:
    image: shaarli/shaarli
    ports:
      # Public HTTP Port:
      - 8080:80
    volumes:
      - shaarli_vol_cache:/var/www/shaarli/cache
      - shaarli_vol_data:/var/www/shaarli/data
